apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: ai-platform
spec:
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
